Traceback (most recent call last):
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tork73/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
a = input("Skriv inn lengden a: ")
b = input("Skriv inn lengden b: ")
h = input("Skriv inn lengden h: ")

a = float(a) # omdefinerer a til Ã¥ vÃ¦re et desimaltall
b = float(b)
h = float(h)

A = (a+b)/2 * h
print("Arealet er", A)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m a [38;5;241m=[39m [38;5;28minput[39m([38;5;124m"[39m[38;5;124mSkriv inn lengden a: [39m[38;5;124m"[39m)
[1;32m      2[0m b [38;5;241m=[39m [38;5;28minput[39m([38;5;124m"[39m[38;5;124mSkriv inn lengden b: [39m[38;5;124m"[39m)
[1;32m      3[0m h [38;5;241m=[39m [38;5;28minput[39m([38;5;124m"[39m[38;5;124mSkriv inn lengden h: [39m[38;5;124m"[39m)

File [0;32m~/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py:1201[0m, in [0;36mKernel.raw_input[0;34m(self, prompt)[0m
[1;32m   1199[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[1;32m   1200[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[0;32m-> 1201[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[1;32m   1202[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[1;32m   1203[0m     [38;5;28mstr[39m(prompt),
[1;32m   1204[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[1;32m   1205[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[1;32m   1206[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m   1207[0m )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

